--------------------------------------------------------
--  Arquivo criado - quinta-feira-março-13-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence CLIENTE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##DW_OLAP"."CLIENTE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence CONCORRENTE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##DW_OLAP"."CONCORRENTE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence LOCAL_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##DW_OLAP"."LOCAL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PRODUTO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##DW_OLAP"."PRODUTO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence TEMPO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##DW_OLAP"."TEMPO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence VENDA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##DW_OLAP"."VENDA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 8301 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "C##DW_OLAP"."CLIENTE" 
   (	"ID_CLIENTE" NUMBER(*,0), 
	"ESTADO_CIVIL" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CONCORRENTE
--------------------------------------------------------

  CREATE TABLE "C##DW_OLAP"."CONCORRENTE" 
   (	"ID_CONCORRENTE" NUMBER(*,0), 
	"ID_TEMPO" NUMBER(*,0), 
	"QUANTIDADE_CONCORRENTE" NUMBER(*,0), 
	"QUANTIDADE" NUMBER(*,0), 
	"VALOR_CONCORRENTE" NUMBER(11,2), 
	"VALOR" NUMBER(11,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOCAL
--------------------------------------------------------

  CREATE TABLE "C##DW_OLAP"."LOCAL" 
   (	"ID_LOCAL" NUMBER(*,0), 
	"ESTADO" VARCHAR2(30 BYTE), 
	"CIDADE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUTO
--------------------------------------------------------

  CREATE TABLE "C##DW_OLAP"."PRODUTO" 
   (	"ID_PRODUTO" NUMBER(*,0), 
	"MODELO" VARCHAR2(30 BYTE), 
	"MARCA" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TEMPO
--------------------------------------------------------

  CREATE TABLE "C##DW_OLAP"."TEMPO" 
   (	"ID_TEMPO" NUMBER(*,0), 
	"QUADRIMESTRE" CHAR(1 BYTE), 
	"ANO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VENDA
--------------------------------------------------------

  CREATE TABLE "C##DW_OLAP"."VENDA" 
   (	"ID_VENDA" NUMBER(*,0), 
	"ID_PRODUTO" NUMBER(*,0), 
	"ID_TEMPO" NUMBER(*,0), 
	"ID_LOCAL" NUMBER(*,0), 
	"ID_CLIENTE" NUMBER(*,0), 
	"QUANTIDADE" NUMBER(*,0), 
	"VALOR" NUMBER(11,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CLIENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##DW_OLAP"."CLIENTE_PK" ON "C##DW_OLAP"."CLIENTE" ("ID_CLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CONCORRENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##DW_OLAP"."CONCORRENTE_PK" ON "C##DW_OLAP"."CONCORRENTE" ("ID_CONCORRENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LOCAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##DW_OLAP"."LOCAL_PK" ON "C##DW_OLAP"."LOCAL" ("ID_LOCAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##DW_OLAP"."TABLE1_PK" ON "C##DW_OLAP"."PRODUTO" ("ID_PRODUTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TEMPO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##DW_OLAP"."TEMPO_PK" ON "C##DW_OLAP"."TEMPO" ("ID_TEMPO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index VENDA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##DW_OLAP"."VENDA_PK" ON "C##DW_OLAP"."VENDA" ("ID_VENDA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CLIENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##DW_OLAP"."CLIENTE_PK" ON "C##DW_OLAP"."CLIENTE" ("ID_CLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CONCORRENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##DW_OLAP"."CONCORRENTE_PK" ON "C##DW_OLAP"."CONCORRENTE" ("ID_CONCORRENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LOCAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##DW_OLAP"."LOCAL_PK" ON "C##DW_OLAP"."LOCAL" ("ID_LOCAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##DW_OLAP"."TABLE1_PK" ON "C##DW_OLAP"."PRODUTO" ("ID_PRODUTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TEMPO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##DW_OLAP"."TEMPO_PK" ON "C##DW_OLAP"."TEMPO" ("ID_TEMPO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index VENDA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##DW_OLAP"."VENDA_PK" ON "C##DW_OLAP"."VENDA" ("ID_VENDA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger CLIENTE_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##DW_OLAP"."CLIENTE_TRG" 
BEFORE INSERT ON CLIENTE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_CLIENTE IS NULL THEN
      SELECT CLIENTE_SEQ.NEXTVAL INTO :NEW.ID_CLIENTE FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##DW_OLAP"."CLIENTE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CONCORRENTE_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##DW_OLAP"."CONCORRENTE_TRG" 
BEFORE INSERT ON CONCORRENTE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_CONCORRENTE IS NULL THEN
      SELECT CONCORRENTE_SEQ.NEXTVAL INTO :NEW.ID_CONCORRENTE FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##DW_OLAP"."CONCORRENTE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger LOCAL_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##DW_OLAP"."LOCAL_TRG" 
BEFORE INSERT ON LOCAL 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_LOCAL IS NULL THEN
      SELECT LOCAL_SEQ.NEXTVAL INTO :NEW.ID_LOCAL FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##DW_OLAP"."LOCAL_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PRODUTO_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##DW_OLAP"."PRODUTO_TRG" 
BEFORE INSERT ON PRODUTO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_PRODUTO IS NULL THEN
      SELECT PRODUTO_SEQ.NEXTVAL INTO :NEW.ID_PRODUTO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##DW_OLAP"."PRODUTO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TEMPO_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##DW_OLAP"."TEMPO_TRG" 
BEFORE INSERT ON TEMPO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_TEMPO IS NULL THEN
      SELECT TEMPO_SEQ.NEXTVAL INTO :NEW.ID_TEMPO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##DW_OLAP"."TEMPO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger VENDA_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##DW_OLAP"."VENDA_TRG" 
BEFORE INSERT ON VENDA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_VENDA IS NULL THEN
      SELECT VENDA_SEQ.NEXTVAL INTO :NEW.ID_VENDA FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##DW_OLAP"."VENDA_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CLIENTE_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##DW_OLAP"."CLIENTE_TRG" 
BEFORE INSERT ON CLIENTE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_CLIENTE IS NULL THEN
      SELECT CLIENTE_SEQ.NEXTVAL INTO :NEW.ID_CLIENTE FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##DW_OLAP"."CLIENTE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CONCORRENTE_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##DW_OLAP"."CONCORRENTE_TRG" 
BEFORE INSERT ON CONCORRENTE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_CONCORRENTE IS NULL THEN
      SELECT CONCORRENTE_SEQ.NEXTVAL INTO :NEW.ID_CONCORRENTE FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##DW_OLAP"."CONCORRENTE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger LOCAL_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##DW_OLAP"."LOCAL_TRG" 
BEFORE INSERT ON LOCAL 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_LOCAL IS NULL THEN
      SELECT LOCAL_SEQ.NEXTVAL INTO :NEW.ID_LOCAL FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##DW_OLAP"."LOCAL_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PRODUTO_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##DW_OLAP"."PRODUTO_TRG" 
BEFORE INSERT ON PRODUTO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_PRODUTO IS NULL THEN
      SELECT PRODUTO_SEQ.NEXTVAL INTO :NEW.ID_PRODUTO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##DW_OLAP"."PRODUTO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TEMPO_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##DW_OLAP"."TEMPO_TRG" 
BEFORE INSERT ON TEMPO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_TEMPO IS NULL THEN
      SELECT TEMPO_SEQ.NEXTVAL INTO :NEW.ID_TEMPO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##DW_OLAP"."TEMPO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger VENDA_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##DW_OLAP"."VENDA_TRG" 
BEFORE INSERT ON VENDA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_VENDA IS NULL THEN
      SELECT VENDA_SEQ.NEXTVAL INTO :NEW.ID_VENDA FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##DW_OLAP"."VENDA_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Function GET_QUARTER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "C##DW_OLAP"."GET_QUARTER" (
    p_date IN DATE
) RETURN CHAR IS
    v_month   NUMBER;
    v_quarter CHAR(1);
BEGIN
    v_month := extract(MONTH FROM p_date);
    v_quarter := '1';
    IF v_month BETWEEN 5 AND 8 THEN
        v_quarter := '1';
    ELSIF v_month BETWEEN 9 AND 12 THEN
        v_quarter := '2';
    END IF;

    RETURN v_quarter;
END;

/
--------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "C##DW_OLAP"."CLIENTE" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "C##DW_OLAP"."CLIENTE" MODIFY ("ESTADO_CIVIL" NOT NULL ENABLE);
  ALTER TABLE "C##DW_OLAP"."CLIENTE" ADD CONSTRAINT "CLIENTE_PK" PRIMARY KEY ("ID_CLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CONCORRENTE
--------------------------------------------------------

  ALTER TABLE "C##DW_OLAP"."CONCORRENTE" MODIFY ("ID_CONCORRENTE" NOT NULL ENABLE);
  ALTER TABLE "C##DW_OLAP"."CONCORRENTE" MODIFY ("ID_TEMPO" NOT NULL ENABLE);
  ALTER TABLE "C##DW_OLAP"."CONCORRENTE" MODIFY ("QUANTIDADE_CONCORRENTE" NOT NULL ENABLE);
  ALTER TABLE "C##DW_OLAP"."CONCORRENTE" MODIFY ("QUANTIDADE" NOT NULL ENABLE);
  ALTER TABLE "C##DW_OLAP"."CONCORRENTE" MODIFY ("VALOR_CONCORRENTE" NOT NULL ENABLE);
  ALTER TABLE "C##DW_OLAP"."CONCORRENTE" MODIFY ("VALOR" NOT NULL ENABLE);
  ALTER TABLE "C##DW_OLAP"."CONCORRENTE" ADD CONSTRAINT "CONCORRENTE_PK" PRIMARY KEY ("ID_CONCORRENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOCAL
--------------------------------------------------------

  ALTER TABLE "C##DW_OLAP"."LOCAL" MODIFY ("ID_LOCAL" NOT NULL ENABLE);
  ALTER TABLE "C##DW_OLAP"."LOCAL" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "C##DW_OLAP"."LOCAL" MODIFY ("CIDADE" NOT NULL ENABLE);
  ALTER TABLE "C##DW_OLAP"."LOCAL" ADD CONSTRAINT "LOCAL_PK" PRIMARY KEY ("ID_LOCAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUTO
--------------------------------------------------------

  ALTER TABLE "C##DW_OLAP"."PRODUTO" MODIFY ("ID_PRODUTO" NOT NULL ENABLE);
  ALTER TABLE "C##DW_OLAP"."PRODUTO" MODIFY ("MODELO" NOT NULL ENABLE);
  ALTER TABLE "C##DW_OLAP"."PRODUTO" MODIFY ("MARCA" NOT NULL ENABLE);
  ALTER TABLE "C##DW_OLAP"."PRODUTO" ADD CONSTRAINT "PRODUTO_PK" PRIMARY KEY ("ID_PRODUTO")
  USING INDEX (CREATE UNIQUE INDEX "C##DW_OLAP"."TABLE1_PK" ON "C##DW_OLAP"."PRODUTO" ("ID_PRODUTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table TEMPO
--------------------------------------------------------

  ALTER TABLE "C##DW_OLAP"."TEMPO" MODIFY ("ID_TEMPO" NOT NULL ENABLE);
  ALTER TABLE "C##DW_OLAP"."TEMPO" MODIFY ("QUADRIMESTRE" NOT NULL ENABLE);
  ALTER TABLE "C##DW_OLAP"."TEMPO" MODIFY ("ANO" NOT NULL ENABLE);
  ALTER TABLE "C##DW_OLAP"."TEMPO" ADD CONSTRAINT "TEMPO_PK" PRIMARY KEY ("ID_TEMPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VENDA
--------------------------------------------------------

  ALTER TABLE "C##DW_OLAP"."VENDA" MODIFY ("ID_VENDA" NOT NULL ENABLE);
  ALTER TABLE "C##DW_OLAP"."VENDA" MODIFY ("ID_PRODUTO" NOT NULL ENABLE);
  ALTER TABLE "C##DW_OLAP"."VENDA" MODIFY ("ID_TEMPO" NOT NULL ENABLE);
  ALTER TABLE "C##DW_OLAP"."VENDA" ADD CONSTRAINT "VENDA_PK" PRIMARY KEY ("ID_VENDA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##DW_OLAP"."VENDA" MODIFY ("ID_LOCAL" NOT NULL ENABLE);
  ALTER TABLE "C##DW_OLAP"."VENDA" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "C##DW_OLAP"."VENDA" MODIFY ("QUANTIDADE" NOT NULL ENABLE);
  ALTER TABLE "C##DW_OLAP"."VENDA" MODIFY ("VALOR" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CONCORRENTE
--------------------------------------------------------

  ALTER TABLE "C##DW_OLAP"."CONCORRENTE" ADD CONSTRAINT "CONCORRENTE_ID_TEMPO_FK" FOREIGN KEY ("ID_TEMPO")
	  REFERENCES "C##DW_OLAP"."TEMPO" ("ID_TEMPO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VENDA
--------------------------------------------------------

  ALTER TABLE "C##DW_OLAP"."VENDA" ADD CONSTRAINT "PRODUTO_FK" FOREIGN KEY ("ID_PRODUTO")
	  REFERENCES "C##DW_OLAP"."PRODUTO" ("ID_PRODUTO") ENABLE;
  ALTER TABLE "C##DW_OLAP"."VENDA" ADD CONSTRAINT "TEMPO_FK" FOREIGN KEY ("ID_TEMPO")
	  REFERENCES "C##DW_OLAP"."TEMPO" ("ID_TEMPO") ENABLE;
  ALTER TABLE "C##DW_OLAP"."VENDA" ADD CONSTRAINT "LOCAL_FK" FOREIGN KEY ("ID_LOCAL")
	  REFERENCES "C##DW_OLAP"."LOCAL" ("ID_LOCAL") ENABLE;
  ALTER TABLE "C##DW_OLAP"."VENDA" ADD CONSTRAINT "CLIENTE_FK" FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES "C##DW_OLAP"."CLIENTE" ("ID_CLIENTE") ENABLE;
